import {action, computed, observable} from "mobx";
import {NumberRange} from "@blueprintjs/core";
import {Table} from "@blueprintjs/table";
import {CARTA} from "carta-protobuf";
import {AppStore} from "stores";
import {RegionWidgetStore, RegionsType} from "./RegionWidgetStore";
import {ProcessedColumnData} from "models";
import {wavelengthToFrequency} from "utilities";

export enum SpectralLineQueryRangeType {
    Range = "Range",
    Center = "Center"
}

export enum SpectralLineQueryUnit {
    GHz = "GHz",
    MHz = "MHz",
    CM = "cm",
    MM = "mm"
}

export enum SpectralLineOptions {
    Formula = "FORMULA",
    Name = "NAME",
    Frequency = "FREQ",
    RedshiftedFrequency = "REDSHIFTED_FREQ",
    QuantumNumber = "QN",
    Intensity = "I",
    AstroFilter = "ASTRO"
}

export interface SpectralLineHeader {
    name: SpectralLineOptions,
    desc: string
}

export enum RedshiftType {
    V = "V",
    Z = "Z"
}

export class SpectralLineOverlayWidgetStore extends RegionWidgetStore {
    @observable queryRangeType: SpectralLineQueryRangeType;
    @observable queryRange: NumberRange;
    @observable queryRangeByCenter: NumberRange;
    @observable queryUnit: SpectralLineQueryUnit;
    @observable isQuerying: boolean;
    @observable headerDataset: SpectralLineHeader[];
    @observable optionsDisplay: Map<SpectralLineOptions, boolean>;
    @observable redshiftType: RedshiftType;
    @observable redshiftSpeed: number;
    @observable queryResultTableRef: Table;
    @observable queryResult: Map<number, ProcessedColumnData>;
    @observable numVisibleRows: number;

    @action setQueryRangeType = (queryRangeType: SpectralLineQueryRangeType) => {
        this.queryRangeType = queryRangeType;
    };

    @action setQueryRange = (queryRange: NumberRange) => {
        this.queryRange = queryRange;
    };

    @action setQueryRangeByCenter = (queryRange: NumberRange) => {
        this.queryRangeByCenter = queryRange;
    };

    @action setQueryUnit = (queryUnit: SpectralLineQueryUnit) => {
        this.queryUnit = queryUnit;
    };

    @action setOptionsDisplay = (option: SpectralLineOptions) => {
        this.optionsDisplay.set(option, !this.optionsDisplay.get(option));
    };

    @action setRedshiftType = (redshiftType: RedshiftType) => {
        this.redshiftType = redshiftType;
     };

    @action setRedshiftSpeed = (speed: number) => {
        if (isFinite(speed)) {
            this.redshiftSpeed = speed;
        }
    };

    @action setQueryResultTableRef(ref: Table) {
        this.queryResultTableRef = ref;
    }

    @action query = () => {
        let valueMin = 0;
        let valueMax = 0;
        if (this.queryRangeType === SpectralLineQueryRangeType.Range) {
            valueMin = this.queryRange[0];
            valueMax = this.queryRange[1];
        } else {
            valueMin = this.queryRangeByCenter[0] - this.queryRangeByCenter[1];
            valueMax = this.queryRangeByCenter[0] + this.queryRangeByCenter[1]
        }

        const freqMHzFrom = this.calculateFreqMHz(valueMin, this.queryUnit);
        const freqMHzTo = this.calculateFreqMHz(valueMax, this.queryUnit);

        if (isFinite(freqMHzFrom) && isFinite(freqMHzTo)) {
            this.isQuerying = true;
            console.log(`&frequency_units=MHz&from=${freqMHzFrom}&to=${freqMHzTo}`);
        }

        // TODO: send query & fetch result
        setTimeout(() => {
            this.isQuerying = false;
            this.headerDataset = [
                {name: SpectralLineOptions.Formula, desc: "Chemical formula of the Species"},
                {name: SpectralLineOptions.Name, desc: "Name of the Species"},
                {name: SpectralLineOptions.Frequency, desc: "Rest Frequency (MHz)"},
                {name: SpectralLineOptions.RedshiftedFrequency, desc: "Redshifted Frequency (MHz)(generated by box on the right)"},
                {name: SpectralLineOptions.QuantumNumber, desc: "Resolved Quantum Number"},
                {name: SpectralLineOptions.Intensity, desc: "Intensity(for JPL/CDMS)"},
                {name: SpectralLineOptions.AstroFilter, desc: "Astronomical Filter(Dark Cloud, Extragalatic, ...)"}
            ];
        }, 1500);
    };

    @computed get displayedColumnHeaders(): Array<CARTA.CatalogHeader> {
        let displayedColumnHeaders = [];
        return displayedColumnHeaders;
    }

    private calculateFreqMHz = (value: number, unit: SpectralLineQueryUnit): number => {
        if (!isFinite(value) || !unit) {
            return null;
        }
        if (unit === SpectralLineQueryUnit.CM) {
            return wavelengthToFrequency(value / 10) / 1e6;
        } else if (unit === SpectralLineQueryUnit.MM) {
            return wavelengthToFrequency(value / 100) / 1e6;
        } else if (unit === SpectralLineQueryUnit.GHz) {
            return value * 1000;
        } else if (unit === SpectralLineQueryUnit.MHz) {
            return value;
        } else {
            return null;
        }
    };

    constructor() {
        super(RegionsType.CLOSED);
        this.queryRangeType = SpectralLineQueryRangeType.Range;
        this.queryRange = [0, 0];
        this.queryRangeByCenter = [0, 0];
        this.queryUnit = SpectralLineQueryUnit.GHz;
        this.isQuerying = false;
        this.headerDataset = [];
        this.optionsDisplay = new Map<SpectralLineOptions, boolean>();
        Object.values(SpectralLineOptions).forEach(option => this.optionsDisplay.set(option, false));
        this.redshiftType = RedshiftType.V;
        this.redshiftSpeed = 0;
        this.queryResultTableRef = undefined;
        this.numVisibleRows = 1;
    }
}
