name: CI
on: push
jobs:
  check-formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
          # Disabling temporarily due to https://github.com/actions/setup-node/issues/516
          # cache: 'npm'
      - run: npm install
      - run: npm run checkformat
