name: CI
on: [push, pull_request]
jobs:

  format-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
          # Disabling temporarily due to https://github.com/actions/setup-node/issues/516
          # cache: 'npm'
      - run: npm install
      - run: npm run checkformat

  node-v12:
    runs-on: [self-hosted, Linux, X64, Docker]
    needs: format-check
    container: carta/frontend-builder
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Fix ownership
        run: |
          chown -R $(id -u):$(id -g) $PWD

      - name: WebAssembly compilation
        shell: bash
        run: |
          source /emsdk/emsdk_env.sh
          ./wasm_libs/build_libs.sh
          npm install
          ./wasm_src/build_wrappers.sh
          ./protobuf/build_proto.sh

      - name: Build with node v12
        shell: bash
        run: |
          n 12
          n exec 12 node -v
          n exec 12 npm install
          n exec 12 npm run build

  node-v14:
    runs-on: [self-hosted, Linux, X64, Docker]
    needs: format-check
    container: carta/frontend-builder
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Fix ownership
        run: |
          chown -R $(id -u):$(id -g) $PWD

      - name: WebAssembly compilation
        shell: bash
        run: |
          source /emsdk/emsdk_env.sh
          ./wasm_libs/build_libs.sh
          npm install
          ./wasm_src/build_wrappers.sh
          ./protobuf/build_proto.sh

      - name: Build with node v14
        shell: bash
        run: |
          n 14
          n exec 14 node -v
          n exec 14 npm install
          n exec 14 npm run build            

  node-v16:
    runs-on: [self-hosted, Linux, X64, Docker]
    needs: format-check
    container: carta/frontend-builder
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Fix ownership
        run: |
          chown -R $(id -u):$(id -g) $PWD

      - name: WebAssembly compilation
        shell: bash
        run: |
          source /emsdk/emsdk_env.sh
          ./wasm_libs/build_libs.sh
          npm install
          ./wasm_src/build_wrappers.sh
          ./protobuf/build_proto.sh

      - name: Build with node v16
        shell: bash
        run: |
          n 16
          n exec 16 node -v
          n exec 16 npm install --legacy-peer-deps
          n exec 16 npm run build            

